name: MD to PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: MD to PDF
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.x
      - run: |
          yarn add md-to-pdf
          npx md-to-pdf ./articles.md
      - uses: actions/upload-artifact@v1
        with:
          name: md-to-pdf
          path: ./articles.pdf
