name: MD to PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: MD to PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.6.0"
      - run: |
          node -v
          npm install
          npm run convert
      - uses: actions/upload-artifact@v1
        with:
          name: md-to-pdf
          path: ./articles.pdf
