name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Set current date
        id: date
        run: |
          DATE=`date +"%Y_%m_%d"`
          echo ::set-output name=datetime::$DATE
      - name: UUIDGEN
        id: uuidgen
        run: |
          UUID=`uuidgen`
          echo ::set-output name=uuid::$UUID
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.1.x
      - run: |
          yarn add md-to-pdf
          npx md-to-pdf ./articles.md --stylesheet ./styles/articles.css
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.uuidgen.outputs.uuid }}
          release_name: ${{ steps.date.outputs.datetime }}
          body: Compiled PDF ${{ github.repository }}
          draft: false
          prerelease: false
      - name: Upload Release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./articles.pdf
          asset_name: articles_${{steps.date.outputs.datetime}}.pdf
          asset_content_type: application/pdf 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: articles
          path: ./articles.pdf
